version: "3"

networks:
  app:
    driver: bridge

volumes:
  database:

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/src/

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    networks:
      - app
    volumes:
      - ./:/src